BACKBONE:
  FREEZE_BN: true
  PRETRAINED: true
  TYPE: vgg16_bn
BINS:
- - -0.1
  - 0.5
- - 0.5
  - 1.5
- - 1.5
  - 2.5
- - 2.5
  - 3.5
- - 3.5
  - 4.5
- - 4.5
  - 5.5
- - 5.5
  - 6.5
- - 6.5
  - 9999
BIN_CENTERS:
- 0.0
- 1.0
- 2.0
- 3.0
- 4.0
- 5.0
- 6.0
- 8.0
CLIP_EBC_HEAD:
  CLIP_MODEL: ViT-B/16
  PRETRAINED: openai
  PROMPT_TYPE: word
  REDUCTION: 16
  WINDOW_SIZE: 16
DATA:
  CROP_SCALE:
  - 0.5
  - 2.0
  CROP_SIZE: 448
  IMG_EXTS:
  - .jpg
  - .png
  NORM_MEAN:
  - 0.48145466
  - 0.4578275
  - 0.40821073
  NORM_STD:
  - 0.26862954
  - 0.26130258
  - 0.27577711
  ROOT: ./data/shb/
  TRAIN_SPLIT: train
  VAL_SPLIT: val
DATASET: shb
DEVICE: cuda
EVAL_STAGE1:
  THRESHOLD: 0.3
EVAL_STAGE3:
  PATCH_SIZE: 224
  STRIDE: 224
  THRESHOLD: 0.3
EXP:
  LOG_INTERVAL: 50
  OUT_DIR: ./checkpoints
  SAVE_BEST: true
LOSS_STAGE2:
  COUNT_LOSS: dmcount
  LABEL_SMOOTHING: 0.0
  TYPE: dace
  WEIGHT_COUNT_LOSS: 1.0
  WEIGHT_OT: 0.1
  WEIGHT_TV: 0.01
NUM_BINS: 8
RUN_NAME: shb
SEED: 42
TRAIN_STAGE1:
  BATCH_SIZE: 32
  EPOCHS: 600
  LR_BACKBONE: 1.0e-05
  LR_HEAD: 0.0005
  NUM_WORKERS: 8
  OPTIMIZER: adamw
  POS_WEIGHT: 1
  VAL_INTERVAL: 5
  WEIGHT_DECAY: 0.0001
TRAIN_STAGE2:
  AMP: true
  BATCH_SIZE: 16
  CLIP_GRAD_NORM: 10.0
  EVAL_FREQ: 1
  LR_BACKBONE: 1.0e-05
  LR_HEAD: 0.0001
  NUM_WORKERS: 8
  OPTIMIZER: adamw
  TOTAL_EPOCHS: 1000
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.0001
TRAIN_STAGE3:
  BATCH_SIZE: 4
  CHECKPOINT_STAGE1: checkpoints/shb/stage1/best_model.pth
  CHECKPOINT_STAGE2: checkpoints/shb/stage2/best_model.pth
  EPOCHS: 400
  LAMBDA_CLIP: 1.0
  LAMBDA_COUNT: 1.0
  LAMBDA_ZIP: 0.1
  LR: 1.0e-05
  LR_BACKBONE: 1.0e-06
  NUM_WORKERS: 4
  WEIGHT_DECAY: 0.0001
